// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Function struct {
	Name	string
	FunctionMetadata
}

func (f *Function) isCallable()	{}

type FunctionProperty struct {
	Of	Value
	Name	string
	FunctionPropertyMetadata
}

func (f *FunctionProperty) isCallable()	{}
