// Code generated by tool/code_generator. DO NOT EDIT.

package code

type LiteralInt struct {
	Value	int64
	LiteralIntMetadata
}

func (l *LiteralInt) isValue()	{}

type LiteralString struct {
	Value	string
	LiteralStringMetadata
}

func (l *LiteralString) isValue()	{}
