// Code generated by tool/code_generator. DO NOT EDIT.

package code

type FieldDef struct {
	Name	string
	Type	Type
	FieldDefMetadata
}

func (f *FieldDef) isDefinition()	{}

type EqualOverride struct {
	OtherName	string
	Block		*Block
	EqualOverrideMetadata
}

func (e *EqualOverride) isCallableDef()	{}

func (e *EqualOverride) isDefinition()	{}

type HashOverride struct {
	Block	*Block
	HashOverrideMetadata
}

func (h *HashOverride) isCallableDef()	{}

type ModelDef struct {
	Name		string
	Fields		[]*FieldDef
	Methods		[]*FunctionDef
	EqualOverride	Optional[*EqualOverride]
	HashOverride	Optional[*HashOverride]
	ModelDefMetadata
}

type Variable struct {
	Name	string
	VariableMetadata
}

func (v *Variable) isValue()	{}

func (v *Variable) isAssignable()	{}

type Property struct {
	Of	Value
	Name	string
	PropertyMetadata
}

func (p *Property) isValue()	{}

func (p *Property) isAssignable()	{}
