// Code generated by tool/code_generator. DO NOT EDIT.

package code

type FieldDef struct {
	Name	string
	Type	Type
	FieldDefMetadata
}

func (f *FieldDef) isDefinition()	{}

type ArgumentDef struct {
	Name	string
	Type	Type
	ArgumentDefMetadata
}

func (a *ArgumentDef) isDefinition()	{}

type MethodDef struct {
	Name		string
	Arguments	[]*ArgumentDef
	Statements	[]Statement
	ReturnType	Type
	MethodDefMetadata
}

type ModelDef struct {
	Name	string
	Fields	[]*FieldDef
	Methods	[]*MethodDef
	ModelDefMetadata
}

type Property struct {
	Of	Value
	Name	string
	PropertyMetadata
}

func (p *Property) isValue()	{}

func (p *Property) isAssignable()	{}

type This struct{ ThisMetadata }

func (t *This) isValue()	{}
