// Code generated by tool/code_generator. DO NOT EDIT.

package code

type FieldDef struct {
	Name	string
	Type	Type
	FieldDefMetadata
}

func (f *FieldDef) isDefinition()	{}

type ArgumentDef struct {
	Name	string
	Type	Type
	ArgumentDefMetadata
}

func (a *ArgumentDef) isDefinition()	{}

type MethodDef struct {
	Function	*FunctionDef
	MethodDefMetadata
}

type ModelDef struct {
	Name	string
	Fields	[]*FieldDef
	Methods	[]*MethodDef
	ModelDefMetadata
}

type Variable struct {
	Name	string
	VariableMetadata
}

func (v *Variable) isValue()	{}

func (v *Variable) isAssignable()	{}

type Property struct {
	Of	Value
	Name	string
	PropertyMetadata
}

func (p *Property) isValue()	{}

func (p *Property) isAssignable()	{}
