// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Module struct {
	Name		string
	Models		[]*ModelDef
	Functions	[]*FunctionDef
	ModuleMetadata
}

type FunctionDef struct {
	Name		string
	Arguments	[]*ArgumentDef
	Statements	[]Statement
	ReturnType	Type
	FunctionDefMetadata
}
