// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Definition interface {
	Node

	isDefinition()
}

type Assignable interface {
	Node

	isAssignable()
}

type Statement interface {
	Node

	isStatement()
}

type Type interface {
	Node

	isType()
}

type Value interface {
	Node

	isValue()
}
