// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Definition interface {
	Node

	isDefinition()
}

type Statement interface {
	Node

	isStatement()
}

type Type interface {
	Node

	isType()
}

type Value interface {
	Node

	isValue()
}

type ConstantValue interface {
	Value

	isConstantValue()
}

type Callable interface {
	Node

	isCallable()
}

type CallableDef interface {
	Node

	isCallableDef()
}
