// Code generated by tool/code_generator. DO NOT EDIT.

package code

type UnaryOperator int

const (
	Not	UnaryOperator	= iota
	Negate
)

type UnaryOperation struct {
	Value		Value
	Operator	UnaryOperator
	UnaryOperationMetadata
}

func (u *UnaryOperation) isValue()	{}

type BinaryOperator int

const (
	Add BinaryOperator = iota
)

type BinaryOperation struct {
	Left, Right	Value
	Operator	BinaryOperator
	BinaryOperationMetadata
}

func (b *BinaryOperation) isValue()	{}
