// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Assignment struct {
	To	Assignable
	From	Value
	AssignmentMetadata
}

func (a *Assignment) isStatement()	{}

type If struct {
	Condition	Value
	Statements	[]Statement
	IfMetadata
}

type ElseIf struct {
	Condition	Value
	Statements	[]Statement
	ElseIfMetadata
}

type Else struct {
	Statements	[]Statement
	ElseMetadata
}

type Conditional struct {
	If	*If
	ElseIfs	[]*ElseIf
	Else	*Else
	ConditionalMetadata
}

func (c *Conditional) isStatement()	{}
