// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Model struct {
	Name	string
	ModelMetadata
}

func (m *Model) isType()	{}

type Primitive int

const (
	Boolean	Primitive	= iota
	Int32
	String
	Void
)

func (p Primitive) isType()	{}
