// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Call struct {
	Function	Callable
	Arguments	[]Value
	CallMetadata
}

func (c *Call) isValue()	{}

type Lookup struct {
	From, Key	Value
	LookupMetadata
}

func (l *Lookup) isValue()	{}

type New struct {
	Model	*Model
	NewMetadata
}

func (n *New) isValue()	{}
