// Code generated by tool/code_generator. DO NOT EDIT.

package code

type Call struct {
	Function	Callable
	Arguments	[]Value
	CallMetadata
}

func (c *Call) isValue()	{}

func (c *Call) isStatement()	{}

type Lookup struct {
	From, Key	Value
	LookupMetadata
}

func (l *Lookup) isValue()	{}

type New struct {
	Model	*Model
	NewMetadata
}

func (n *New) isValue()	{}

type Length struct {
	Value	Value
	LengthMetadata
}

func (l *Length) isValue()	{}

type SetContains struct {
	Set	Value
	Value	Value
	SetContainsMetadata
}

func (s *SetContains) isValue()	{}

type Pop struct {
	Value	Value
	PopMetadata
}

func (p *Pop) isValue()	{}

func (p *Pop) isStatement()	{}
