// Code generated by tool/generator. DO NOT EDIT.
// Run `just gen` to regenerate this file.

package ast

type Optional[T any] struct {
	value T
	set   bool
}

func OptionalWithValue[T any](value T) Optional[T] {
	return Optional[T]{
		value: value,
		set:   true,
	}
}

func (o Optional[T]) Value() T {
	return o.value
}

func (o Optional[T]) IsSet() bool {
	return o.set
}
